const dellData = {
  overallData: {
    productLifespan: {
      "Lattitude 5530": {
        yearOne: 1,
        yearTwo: 2,
        yearThree: 4,
        yearFour: 5,
        yearFive: 10,
        yearSix: 9,
        yearSeven: 5,
        yearEight: 3,
        yearNine: 1,
        yearTen: 0,
      },
      "Lattitude 3300": {
        yearOne: 0,
        yearTwo: 2,
        yearThree: 4,
        yearFour: 6,
        yearFive: 10,
        yearSix: 6,
        yearSeven: 4,
        yearEight: 2,
        yearNine: 1,
        yearTen: 0,
      },
      "Lattitude 3420": {
        yearOne: 0,
        yearTwo: 1,
        yearThree: 1,
        yearFour: 3,
        yearFive: 7,
        yearSix: 11,
        yearSeven: 9,
        yearEight: 6,
        yearNine: 4,
        yearTen: 1,
      },
      "Lattitude 3520": {
        yearOne: 1,
        yearTwo: 2,
        yearThree: 3,
        yearFour: 7,
        yearFive: 6,
        yearSix: 10,
        yearSeven: 5,
        yearEight: 3,
        yearNine: 1,
        yearTen: 0,
      },
      "Lattitude 3330": {
        yearOne: 1,
        yearTwo: 3,
        yearThree: 4,
        yearFour: 4,
        yearFive: 8,
        yearSix: 10,
        yearSeven: 7,
        yearEight: 6,
        yearNine: 3,
        yearTen: 0,
      },
      "Inspiron 13": {
        yearOne: 1,
        yearTwo: 3,
        yearThree: 5,
        yearFour: 9,
        yearFive: 9,
        yearSix: 11,
        yearSeven: 8,
        yearEight: 5,
        yearNine: 3,
        yearTen: 1,
      },
      "Inspiron 14": {
        yearOne: 0,
        yearTwo: 2,
        yearThree: 2,
        yearFour: 6,
        yearFive: 7,
        yearSix: 8,
        yearSeven: 5,
        yearEight: 3,
        yearNine: 1,
        yearTen: 0,
      },
      "Inspiron 16 Plus": {
        yearOne: 1,
        yearTwo: 2,
        yearThree: 4,
        yearFour: 7,
        yearFive: 9,
        yearSix: 11,
        yearSeven: 12,
        yearEight: 7,
        yearNine: 3,
        yearTen: 1,
      },
      "XPS 13": {
        yearOne: 1,
        yearTwo: 3,
        yearThree: 5,
        yearFour: 7,
        yearFive: 9,
        yearSix: 11,
        yearSeven: 9,
        yearEight: 7,
        yearNine: 4,
        yearTen: 3,
      },
      "XPS 13 Plus": {
        yearOne: 1,
        yearTwo: 2,
        yearThree: 3,
        yearFour: 5,
        yearFive: 9,
        yearSix: 10,
        yearSeven: 9,
        yearEight: 5,
        yearNine: 3,
        yearTen: 1,
      },
      "XPS 15": {
        yearOne: 0,
        yearTwo: 3,
        yearThree: 4,
        yearFour: 6,
        yearFive: 10,
        yearSix: 9,
        yearSeven: 7,
        yearEight: 5,
        yearNine: 3,
        yearTen: 1,
      },
      "XPS 17": {
        yearOne: 1,
        yearTwo: 3,
        yearThree: 4,
        yearFour: 5,
        yearFive: 9,
        yearSix: 10,
        yearSeven: 9,
        yearEight: 5,
        yearNine: 3,
        yearTen: 0,
      },
      "XPS Desktop": {
        yearOne: 0,
        yearTwo: 1,
        yearThree: 3,
        yearFour: 8,
        yearFive: 9,
        yearSix: 10,
        yearSeven: 7,
        yearEight: 6,
        yearNine: 3,
        yearTen: 1,
      },
    },
    proportionRecycled: {
      "Amount Recycled": {
        2010: 10,
        2011: 12,
        2012: 15,
        2013: 17,
        2014: 22,
        2015: 23,
        2016: 25,
        2017: 30,
        2018: 31,
        2019: 32,
        2020: 33,
        2021: 34,
      },
      "Amount Discarded": {
        2010: 1,
        2011: 2,
        2012: 5,
        2013: 7,
        2014: 2,
        2015: 3,
        2016: 5,
        2017: 3,
        2018: 1,
        2019: 3,
        2020: 3,
        2021: 4,
      },
    },
    demographics: {
      gender: {
        "% Recycled by Gender": {
          percentMale: 56,
          percentFemale: 43,
        },
        "% Discarded by Gender": {
          percentMale: 44,
          percentFemale: 57,
        },
      },
      region: {
        "% Recycled by Region": {
          EMEA: 75,
          DAO: 67,
          APJ: 58,
        },
        "% Discarded by Region": {
          EMEA: 25,
          DAO: 33,
          APJ: 42,
        },
      },
      age: {
        "% Recycled by Age": {
          below16: 17,
          from16to20: 54,
          from21to30: 45,
          from31to40: 28,
          from41to50: 38,
          above50: 10,
        },
        "% Decarded by Age": {
          below16: 83,
          from16to20: 46,
          from21to30: 55,
          from31to40: 72,
          from41to50: 62,
          above50: 90,
        },
      },
    },
  },
  products: {
    lattitude: {
      lifespan: {
        // labels: ["Year 1", "Year 2", "Year 3", "Year 4", "Year 5"],
        // datapoints: [12, 6, 4, 2, 1],

        yearOne: 1,
        yearTwo: 2,
        yearThree: 4,
        yearFour: 7,
        yearFive: 11,
        yearSix: 8,
        yearSeven: 4,
        yearEight: 3,
        yearNine: 2,
        yearTen: 1,
      },
      productLifespan: {
        "Lattitude 5530": {
          yearOne: 1,
          yearTwo: 2,
          yearThree: 4,
          yearFour: 5,
          yearFive: 10,
          yearSix: 9,
          yearSeven: 5,
          yearEight: 3,
          yearNine: 1,
          yearTen: 0,
        },
        "Lattitude 3300": {
          yearOne: 0,
          yearTwo: 2,
          yearThree: 4,
          yearFour: 6,
          yearFive: 10,
          yearSix: 6,
          yearSeven: 4,
          yearEight: 2,
          yearNine: 1,
          yearTen: 0,
        },
        "Lattitude 3420": {
          yearOne: 0,
          yearTwo: 1,
          yearThree: 1,
          yearFour: 3,
          yearFive: 7,
          yearSix: 11,
          yearSeven: 9,
          yearEight: 6,
          yearNine: 4,
          yearTen: 1,
        },
        "Lattitude 3520": {
          yearOne: 1,
          yearTwo: 2,
          yearThree: 3,
          yearFour: 7,
          yearFive: 6,
          yearSix: 10,
          yearSeven: 5,
          yearEight: 3,
          yearNine: 1,
          yearTen: 0,
        },
        "Lattitude 3330": {
          yearOne: 1,
          yearTwo: 3,
          yearThree: 4,
          yearFour: 4,
          yearFive: 8,
          yearSix: 10,
          yearSeven: 7,
          yearEight: 6,
          yearNine: 3,
          yearTen: 0,
        },
      },
      percentageRecycled: 50,
      proportionRecycled: {
        "Amount Recycled": {
          2010: 1,
          2011: 2,
          2012: 5,
          2013: 7,
          2014: 7,
          2015: 7,
          2016: 9,
          2017: 11,
          2018: 13,
          2019: 3,
          2020: 8,
          2021: 9,
        },
        "Amount Discarded": {
          2010: 7,
          2011: 6,
          2012: 6,
          2013: 6,
          2014: 5,
          2015: 5,
          2016: 5,
          2017: 3,
          2018: 2,
          2019: 1,
          2020: 1,
          2021: 1,
        },
      },
      demographics: {
        gender: {
          "% Recycled by Gender": {
            percentMale: 56,
            percentFemale: 44,
          },
          "% Discarded by Gender": {
            percentMale: 44,
            percentFemale: 56,
          },
        },
        region: {
          "% Recycled by Region": {
            EMEA: 80,
            DAO: 52,
            APJ: 75,
          },
          "% Discarded by Region": {
            EMEA: 20,
            DAO: 48,
            APJ: 25,
          },
        },
        age: {
          "% Recycled by Age": {
            below16: 80,
            from16to20: 54,
            from21to30: 86,
            from31to40: 76,
            from41to50: 54,
            above50: 37,
          },
          "% Decarded by Age": {
            below16: 20,
            from16to20: 46,
            from21to30: 14,
            from31to40: 24,
            from41to50: 46,
            above50: 63,
          },
        },
      },
    },
    inspiron: {
      lifespan: {
        // labels: ["Year 1", "Year 2", "Year 3", "Year 4", "Year 5"],
        // datapoints: [12, 6, 4, 2, 1],

        yearOne: 1,
        yearTwo: 2,
        yearThree: 4,
        yearFour: 7,
        yearFive: 10,
        yearSix: 8,
        yearSeven: 5,
        yearEight: 3,
        yearNine: 1,
        yearTen: 0,
      },
      productLifespan: {
        "Inspiron 13": {
          yearOne: 1,
          yearTwo: 3,
          yearThree: 5,
          yearFour: 9,
          yearFive: 9,
          yearSix: 11,
          yearSeven: 8,
          yearEight: 5,
          yearNine: 3,
          yearTen: 1,
        },
        "Inspiron 14": {
          yearOne: 0,
          yearTwo: 2,
          yearThree: 2,
          yearFour: 6,
          yearFive: 7,
          yearSix: 8,
          yearSeven: 5,
          yearEight: 3,
          yearNine: 1,
          yearTen: 0,
        },
        "Inspiron 16 Plus": {
          yearOne: 1,
          yearTwo: 2,
          yearThree: 4,
          yearFour: 7,
          yearFive: 9,
          yearSix: 11,
          yearSeven: 12,
          yearEight: 7,
          yearNine: 3,
          yearTen: 1,
        },
      },
      percentageRecycled: 50,
      proportionRecycled: {
        "Amount Recycled": {
          2010: 3,
          2011: 2,
          2012: 5,
          2013: 5,
          2014: 6,
          2015: 7,
          2016: 8,
          2017: 8,
          2018: 8,
          2019: 9,
          2020: 9,
          2021: 9,
        },
        "Amount Discarded": {
          2010: 6,
          2011: 6,
          2012: 5,
          2013: 5,
          2014: 3,
          2015: 4,
          2016: 3,
          2017: 3,
          2018: 1,
          2019: 2,
          2020: 3,
          2021: 3,
        },
      },
      demographics: {
        gender: {
          "% Recycled by Gender": {
            percentMale: 69,
            percentFemale: 75,
          },
          "% Discarded by Gender": {
            percentMale: 31,
            percentFemale: 25,
          },
        },
        region: {
          "% Recycled by Region": {
            EMEA: 71,
            DAO: 25,
            APJ: 43,
          },
          "% Discarded by Region": {
            EMEA: 29,
            DAO: 75,
            APJ: 57,
          },
        },
        age: {
          "% Recycled by Age": {
            below16: 19,
            from16to20: 47,
            from21to30: 76,
            from31to40: 76,
            from41to50: 59,
            above50: 33,
          },
          "% Decarded by Age": {
            below16: 81,
            from16to20: 53,
            from21to30: 24,
            from31to40: 24,
            from41to50: 41,
            above50: 67,
          },
        },
      },
    },
    xps: {
      lifespan: {
        // labels: ["Year 1", "Year 2", "Year 3", "Year 4", "Year 5"],
        // datapoints: [12, 6, 4, 2, 1],

        yearOne: 1,
        yearTwo: 3,
        yearThree: 5,
        yearFour: 9,
        yearFive: 10,
        yearSix: 10,
        yearSeven: 6,
        yearEight: 3,
        yearNine: 2,
        yearTen: 1,
      },
      productLifespan: {
        "XPS 13": {
          yearOne: 1,
          yearTwo: 3,
          yearThree: 5,
          yearFour: 7,
          yearFive: 9,
          yearSix: 11,
          yearSeven: 9,
          yearEight: 7,
          yearNine: 4,
          yearTen: 3,
        },
        "XPS 13 Plus": {
          yearOne: 1,
          yearTwo: 2,
          yearThree: 3,
          yearFour: 5,
          yearFive: 9,
          yearSix: 10,
          yearSeven: 9,
          yearEight: 5,
          yearNine: 3,
          yearTen: 1,
        },
        "XPS 15": {
          yearOne: 0,
          yearTwo: 3,
          yearThree: 4,
          yearFour: 6,
          yearFive: 10,
          yearSix: 9,
          yearSeven: 7,
          yearEight: 5,
          yearNine: 3,
          yearTen: 1,
        },
        "XPS 17": {
          yearOne: 1,
          yearTwo: 3,
          yearThree: 4,
          yearFour: 5,
          yearFive: 9,
          yearSix: 10,
          yearSeven: 9,
          yearEight: 5,
          yearNine: 3,
          yearTen: 0,
        },
        "XPS Desktop": {
          yearOne: 0,
          yearTwo: 1,
          yearThree: 3,
          yearFour: 8,
          yearFive: 9,
          yearSix: 10,
          yearSeven: 7,
          yearEight: 6,
          yearNine: 3,
          yearTen: 1,
        },
      },
      percentageRecycled: 50,
      proportionRecycled: {
        "Amount Recycled": {
          2010: 1,
          2011: 1,
          2012: 1,
          2013: 3,
          2014: 2,
          2015: 3,
          2016: 5,
          2017: 3,
          2018: 3,
          2019: 4,
          2020: 5,
          2021: 5,
        },
        "Amount Discarded": {
          2010: 5,
          2011: 5,
          2012: 5,
          2013: 4,
          2014: 4,
          2015: 3,
          2016: 1,
          2017: 5,
          2018: 3,
          2019: 3,
          2020: 2,
          2021: 4,
        },
      },
      demographics: {
        gender: {
          "% Recycled by Gender": {
            percentMale: 46,
            percentFemale: 37,
          },
          "% Discarded by Gender": {
            percentMale: 54,
            percentFemale: 63,
          },
        },
        region: {
          "% Recycled by Region": {
            EMEA: 78,
            DAO: 19,
            APJ: 60,
          },
          "% Discarded by Region": {
            EMEA: 22,
            DAO: 81,
            APJ: 40,
          },
        },
        age: {
          "% Recycled by Age": {
            below16: 11,
            from16to20: 45,
            from21to30: 55,
            from31to40: 66,
            from41to50: 68,
            above50: 37,
          },
          "% Decarded by Age": {
            below16: 89,
            from16to20: 55,
            from21to30: 45,
            from31to40: 34,
            from41to50: 32,
            above50: 63,
          },
        },
      },
    },
  },
};
